FROM registry.fedoraproject.org/fedora:latest

# Install OS packages
COPY ./*.sh /opt/scripts/
RUN chmod +x /opt/scripts/*.sh

RUN /opt/scripts/01-install-os-packages.sh
RUN /opt/scripts/02-install-other-packages.sh

RUN rm -rf /var/cache /var/log/dnf* /var/log/yum.*
