FROM docker.io/fedora:latest

RUN set -x \
	# OS upgrade
	&& dnf upgrade -y \
	# Repos
	&& dnf install -y dnf-plugins-core \
	&& dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo \
	# Groups
	&& dnf groupinstall -y "Development Tools" "Development Libraries" \
	# OS packages
	&& dnf install -y \
		sudo make htop procps-ng net-tools iputils iproute bind9-next-utils hostname \
		terraform \
		python3-pip \
		curl wget \
		git make \
		golang \
		vim nano \
		rust cargo \
		ansible \
		podman \
	# Python packages
	&& pip install \
		ansible-navigator \
		ansible-creator \
		ansible-lint

ARG USER=coder
RUN set -x \
	&& useradd --groups wheel --no-create-home --shell /bin/bash ${USER} \
	&& echo "${USER} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/${USER} \
	&& chmod 0440 /etc/sudoers.d/${USER}

USER ${USER}
WORKDIR /home/${USER}
